const express = require('express');
const router = express.Router();

const stocksRouter = require('./stocks');
const marketRouter = require('./market');
const analysisRouter = require('./analysis');
const portfolioRouter = require('./portfolio');
const userRouter = require('./user');
const newsRouter = require('./news');
const sectorsRouter = require('./sectors');
const screenerRouter = require('./screener');
const recommendationRouter = require('./recommendation');
const hotMarketRouter = require('./hotMarket');
const themesRouter = require('./themes');
const sentimentRouter = require('./sentiment');
const level2Router = require('./level2');
const aiResearchRouter = require('./aiResearch');
const quantRouter = require('./quant');
const researchDecisionRouter = require('./researchDecision');
const chartCoachRouter = require('./chartCoach');
const capitalFlowRouter = require('./capitalFlow');
const mobileRouter = require('./mobile');
const dataHealthRouter = require('./dataHealth');
const industryChainRouter = require('./industryChain');
const marketBoardsRouter = require('./marketBoards');
const externalResearchBatchesRouter = require('./externalResearchBatches');
const marketInstitutionalFlowRouter = require('./marketInstitutionalFlow');
const eastmoneyEtfDailyRouter = require('./eastmoneyEtfDaily');

router.use('/api', stocksRouter);
router.use('/api', marketRouter);
router.use('/api', analysisRouter);
router.use('/api', userRouter);
router.use('/api', newsRouter);
router.use('/api', sectorsRouter);
router.use('/api', screenerRouter);
router.use('/api', recommendationRouter);
router.use('/api', hotMarketRouter);
router.use('/api', themesRouter);
router.use('/api', sentimentRouter);
router.use('/api', level2Router);
router.use('/api', aiResearchRouter);
router.use('/api', quantRouter);
router.use('/api', researchDecisionRouter);
router.use('/api', chartCoachRouter);
router.use('/api', capitalFlowRouter);
router.use('/api', require('./sectorRotation'));
router.use('/api', mobileRouter);
router.use('/api', dataHealthRouter);
router.use('/api', industryChainRouter);
router.use('/api', marketBoardsRouter);
router.use('/api', externalResearchBatchesRouter);
router.use('/api', marketInstitutionalFlowRouter);
router.use('/api', eastmoneyEtfDailyRouter);
router.use('/api/portfolio', portfolioRouter);

module.exports = router;
